version: '3'
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: 'orca'
            POSTGRES_PASSWORD: 'test1234'
            POSTGRES_DB: 'orca'
        ports:
            - "127.0.0.1:5432:5432"
    nats:
        expose:
            - "4222"
        ports:
            - "127.0.0.1:8222:8222"
            - "127.0.0.1:4222:4222"
        image: nats
        command: "-p 4222 -m 8222 -DV"
    orca:
        build: ./orca
        environment:
            DB_HOST: 'db'
            DB_USER: 'orca'
            DB_PASS: 'test1234'
            DB_NAME: 'orca'
            NATS_URL: 'nats://nats:4222'
        ports:
            - "127.0.0.1:1337:1337"
        command: "run -host 0.0.0.0 -port 1337"
    baseline:
        build: ./baseline
        environment:
            NATS_URL: 'nats:4222'
            PYTHONUNBUFFERED: '1'
    syntribos:
        build: ./syntribos
        environment:
            NATS_URL: 'nats:4222'
            PYTHONUNBUFFERED: '1'
